Civil-Service-Human-Resources/lpg-services

- component/User.html
- page/profile/index.html
- src/server.ts
when/if logged in, /login redirects to /profile - which shows { email address, department, profession, grade }
> 330-show-user-profile-after-login

- page/sign-in/index.html
- src/server.ts
A few tweaks to fix login after moving to lpg.dev.cshr.digital. Not perfect, but working.
> #303 user can login to csl platform

- .dockerignore
- Dockerfile
- config/custom-environment-variables.json
- config/default.json
- page/sign-in/index.html
- src/server.ts
Externalise identity config and add Dockerfile.
> #344 Dockerise LPG UI

- service/ui/component/Recommended.html
- service/ui/page/search/index.html
> refactor recommended (no need to pass user object to subcomponent)

- test/headless/src/extension/helper.ts
- test/headless/src/page/globals.ts
- test/headless/src/page/learningPlan.ts
- test/headless/src/test/config.ts
- test/headless/src/test/feedback.ts
- test/headless/src/test/learningPlan.ts
Added BASE_URL, fixed visible method, updated selectors
> feedback-fixes

- src/ui/assets/styles/components/_footer.scss
> 519 tweaking footer top border

- src/lib/ui/template.ts
- src/ui/assets/styles/main.scss
> re add pagination component

- package.json
- src/locale/en.json
- src/management-ui/filestore.ts
> bug/LPFG-96-Management setting startpage not set correctly + mimetypes

- src/lib/model.ts
- src/ui/controllers/suggestion.ts
Management method file location fix
> Don't suggest learning someone's already completed

- src/lib/config/index.ts
- src/lib/model.ts
- src/locale/en.json
- src/management-ui/page/courses/modules/face-to-face.html
Course price calculated from module
Added price field to face to face module form
> LPFG-97-Cost-missing-from-classroom-base-course

- src/ui/component/Footer.html
- src/ui/page/privacy.html
- src/ui/server.ts
**PR includes**
* Privacy page and endpoint
> feature/LPFG-185 Privacy page

- package.json
- src/management-ui/server.ts
- src/ui/server.ts
checks every field in req.body and escapes
> bug/LPFG-235 express-validator

- src/management-ui/server.ts
- src/ui/server.ts
Changing required role names for UI and Management
> FIx/LPFG-349 - Changing required roles for ui and management

- src/management-ui/component/Layout.html
- src/ui/assets/js/main.js
- src/ui/assets/styles/components/_header.scss
- src/ui/component/Layout.html
- src/ui/component/Page.html
- src/ui/controllers/home.ts
- src/ui/page/cookies.html
- src/ui/server.ts
- adding cookies page and banner (cookie page has fairly basic styling for now, but may need stylised in line with gds in future)
- adding cookie controller to set cookie seen_cookie_message value to true
- js to check value of cookie and hide banner accordingly
- if user's browser has javascript turned off, the message should always appear
> Feature/LPFG-13 - Adding cookie page and banner

- src/lib/learnerrecord.ts
- src/lib/registry.ts
- src/locale/en.json
- src/ui/controllers/user.ts
This also has a small but vital change of a method to the learner-record changing from a GET to a PATCH
> Lpfg 419  error messages not showing

- docker-compose.yaml
- src/lib/learnerrecord.ts
- src/management-ui/controllers/bookings/index.ts
This update is required to fix reporting.
> Update learner record supporting modified activityids.

- src/management-ui/filestore.ts
- src/ui/controllers/course/index.ts
- src/ui/page/course/video.html
This needs to merge with 'Lpfg 738 post the file form to learning catalogue' from lpg-management and lpg-learning-catalogue
Added new elearning url structure to index.ts
Fixed video type checking in video.html
> Lpfg 738 post the file form to learning catalogue

- src/lib/model.ts
- src/ui/controllers/booking/booking.ts
- src/ui/controllers/course/index.ts
- src/ui/controllers/search.ts
- src/ui/controllers/user.ts
Updated calls to CSRS for organisations.
> LPFG-820: Update lpg-services to call new organisationalUnit endpoint in CSRS

- docker-compose.yaml
- src/management-ui/assets/styles/components/_discite.scss
- src/management-ui/assets/styles/index.scss
- src/management-ui/component/Page.html
- src/ui/assets/styles/components/_badge.scss
- src/ui/assets/styles/components/_discite.scss
- src/ui/assets/styles/main.scss
- src/ui/component/Page.html
- src/ui/page/error.html
- src/ui/page/error/404.html
- Added margin to top of notice in face 2 face overview
- Forced all text to be capitalised on all badges (Fixing mixed case on some badges)
- Fixed crashing header issues on course listings
- Floating footer is an issue in repo 'identity-record' and has been fixed in a separate sub task/branch
> Lpfg 533 Front end bug fixes

- src/lib/model.ts
- src/lib/ui/courseCallToAction.ts
A fix that stops all required courses appearing as in every departments learning plan.
Fixed 'isInLearningPlan' being hard coded to true in courseControllerToAction.ts
Fixed audiences getting set to empty array in Course in model.ts
> Fix/LPFG-799-v2 Fixed bug

- Jenkinsfile
- docker-compose.yaml
- src/ui/assets/styles/components/_discite.scss
- src/ui/page/privacy.html
- src/ui/server.ts
- updating privacy policy content
> LPFG-900: adding privacy policy

- src/ui/component/Header.html
- src/ui/component/SuggestionsSection.html
- src/ui/page/suggested.html
- updating suggestions link to use codes instead of names
- adding new smart survey link
> fix-suggestions-and-survey

- src/lib/config/index.ts
- src/ui/page/search/index.html
- src/ui/server.ts
- fixing feedback issue as js was being excluded from the app's CSP
- fixing pagination search parameters
> LPFG-916: adding self to csp, fixing pagination issue

- README.md
- update readme to include lpgregistry login step
> chore: update readme to include lpgregistry login step

- src/locale/en.json
- src/ui/assets/styles/common/_variables.scss
- src/ui/assets/styles/components/_suggestions.scss
- src/ui/assets/styles/main.scss
- src/ui/component/SuggestionsSection.html
- src/ui/controllers/suggestion.ts
- src/ui/page/suggested.html
Changed home_page_suggestions value in en.json
Added new colour variable to the (previously empty???) varaibles.scss
Added styling for suggestions quick links
Mobile responsiveness added
Included an ID attribute to the H2 headings on SuggestedSection component
Updated course object to distinguish between primaryAreaOfWork and other areasOfWork
Added html for quick links in suggested.html
> Suggestions for you v2

- src/ui/component/disciteParts/DisciteModuleActions.html
- src/ui/component/disciteParts/DisciteModuleProperties.html
- links now open in a new tab! 🚀
> LPFG-704: Links open in a new tab

- src/ui/assets/styles/main.scss
- src/ui/component/TypeAhead.html
- Changed placeholder text for organisations typeahead
> changed typeahead placeholder text

- docker-compose.yaml
- run_backend.sh
- updating docker-compose with images for release
- adding a run_backend script to ensure you're logged into acr before attempting to dowload images with docker-compose up
> chore: update-dc-1911

- package.json
- src/lib/config/index.ts
- src/ui/server.ts
- adding app insights to lpg-services for azure (https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs)
- `do not merge` while Rob tests on Integration
> LPFG-851: app insights

- src/lib/model.ts
- src/ui/assets/styles/main.scss
- src/ui/component/LearningRecordTable.html
- src/ui/component/disciteParts/DisciteModuleActions.html
- new branch to resolve merge conflicts of LPFG-892
- added suggestions for you headers and quick links on suggestions for you page
> LPFG-893-V2

- docker-compose.yaml
- updating dc to have search, organisations, learner-record work
> chore-update-dc-2911

- src/ui/assets/js/govuk_frontend_toolkit/govuk/govuk-template.js
- src/ui/component/Header.html
- src/ui/component/Nav.html
- src/ui/component/Tile.html
- src/ui/component/disciteParts/DisciteCourseProperties.html
- src/ui/page/profile/view.html
- added (hidden) course title to add/remove links in order for them to be more meaningful to screen readers
- made the hidden text for change primary area of work/ change other areas of work unique so that screen readers can tell them apart
> LPFG-1011 make ambiguous links more meaningful

- src/ui/component/Checkboxes.html
- src/ui/component/NewRadios.html
- src/ui/component/ProfileEditForm.html
- src/ui/component/Selects.html
- src/ui/page/profile/edit.html
- added legend tag and content to top of profile forms, 
- fixed id and label for properties to prevent breaking in screen readers
> LPFG-1010 Fixed profile forms for screen readers

- src/ui/assets/styles/components/_results.scss
- src/ui/controllers/learning-record/index.ts
- src/ui/page/learning-record/course-result.html
**This also includes LPFG-951 Course Completion and LPFG-1060**
When a module is completed a module complete screen is shown, with a button to take the learner back to the course overview page.
When all modules are completed a course complete screen is shown with a link to the learner record.
The completion banner is now blue and doesn't apply title case to the title.
> Lpfg 950 module completion

- src/ui/component/LearningRecordTable.html
- Changed learner record completed learning header from 'Completion date' to 'Date completed'
> LPFG-1051 changed completed module text

- src/ui/page/learning-record/feedback-list.html
> LPFG-1055 Change feedback text

- src/ui/assets/styles/components/_badge.scss
- src/ui/assets/styles/components/_results.scss
- Changed the case of status badges. I.e from 'In Progress' to 'In progress'
> LPFG-1057 Badge text change

- src/lib/model.ts
- src/ui/page/booking/choose-date.html
**Needs to be merge with LPFG-669 from learner-record and learning-catalogue**
This hides events that are cancelled so that learners can't book onto them.
- model.ts: Added status to Event, if the status is null then the event is set to active so that old events will till appear.
- choose-date.html: hide events that are cancelled
> Lpfg 669 event status

- src/locale/en.json
- src/ui/page/learning-record/index.html
- src/ui/server.ts
- Changed page text for learner record
> LPFG-1165 Change learning record text

- docker-compose.yaml
- src/ui/assets/styles/common/_global.scss
- src/ui/component/Banner.html
- src/ui/page/profile/view.html
- styling edits for profile confirmation; centre aligned text; evened out the padding at top & bottom of banner
> LPFG-1183 Profile confirmation

- package.json
- src/ui/component/DisciteFeedback.html
- src/ui/page/learning-record/feedback-list.html
- Fixed undefined cost on feedback page
> LPFG-1190 fixed course price on feedback page

- docker-compose.yaml
- src/ui/page/learning-record/feedback.html
> LPFG-1195 feedback wording

- src/ui/assets/styles/components/_discite.scss
- Added capitalisation for first letter on all course/module property items
> LPFG-1196 capitalised file course property

- .gitignore
- docker-compose.yaml
- src/ui/assets/styles/components/_search.scss
- changed padding on input to correctly position placeholder
> LPFG-1217 fixed placeholder positioning

- src/ui/assets/styles/common/_global.scss
- Added capitalisation for all course property items
> LPFG - Capitalised course type first letter

- docker-compose.yaml
- updating docker compose when new release images
> Updating docker compose

- docker-compose.yaml
> updating-dc-1502

- src/ui/page/contact-us.html
> LC-134: updating content on contact us

- src/lib/model.ts
- src/ui/component/DisciteCourse.html
- src/ui/page/suggested.html
**Needs to be merged with LPFG-1238 in learning catalogue**
**Also any existing courses with a frequency need to be updated manually**
**model.ts**: Updated frequency type to Duration, updated frequency class to perform increments and decrements with a duration instead of the old enum
> Lpfg 1248 pre reading audience

- src/ui/controllers/profile.ts
- src/ui/page/profile/lineManager.html
- line manager self-sign up screen would hang if email doesnt exist
- add error handling based upon error codes to redirect to page with correct error message
> LC-135: error handling for line manager self sign up

- docker-compose.yaml
- src/ui/assets/styles/common/_global.scss
- src/ui/page/search/index.html
- Added 'No results' message to search results page if no results present.
> LPFG-1170 No results message search results page

- docker-compose.yaml
> chore-2803-docker-compose

- src/ui/assets/styles/components/_govuk-related-items.scss
- src/ui/assets/styles/components/_leftSearchBox.scss
- src/ui/component/LeftSearchBox.html
- Reduced headings font-size
- Reduced headings margin-top
- Lighter background applied to headers
> LPFG-1231 filter header changes

- src/ui/assets/styles/common/_global.scss
- src/ui/assets/styles/components/_leftSearchBox.scss
- src/ui/component/LeftSearchBox.html
- added show/hide functionality for mobile search filters.
> LPFG-1235 Mobile search

- src/ui/page/learning-record/index.html
- added link to CSL from learning record page
> LPFG-1228 link to CSL

- src/ui/assets/styles/common/_global.scss
- Removed block of padding beneath content across all pages
- Tested on desktop and mobile
> LC-183: Removed block of padding

- src/ui/component/DisciteCourse.html
- changing casing of status in comparator
> LC-139: casing of status

- docker-compose.yaml
> Chore 0104 docker compose

- src/locale/en.json
- src/ui/component/DisciteCourse.html
- src/ui/component/disciteParts/DisciteModuleProperties.html
- src/ui/page/booking/cancel-booking.html
- get state instead of booking status
> LC-139-status-v2

- src/lib/service/catalog/index.ts
- src/locale/en.json
- src/ui/controllers/suggestion.ts
> LC-191: grade suggestions

- src/lib/config/index.ts
- src/lib/config/passport.ts
- src/lib/identity.ts
- src/ui/controllers/user.ts
- src/ui/server.ts
- adding req.logout to sign-in to ensure user is doing a fresh login when they submit credentials from identity
- calling revoke endpoint during sign-out flow
> LC-163: UI auth issues

- src/ui/assets/styles/components/_leftSearchBox.scss
- src/ui/component/LeftSearchBox.html
- src/ui/controllers/user.ts
> LC-182-search-filters

- docker-compose.yaml
> chore: updating docker-compose with release images

- docker-compose.yaml
- src/lib/ui/profileChecker.ts
- src/ui/controllers/errorHandler.ts
- src/ui/controllers/home.ts
- src/ui/page/suggested.html
- more error handling for auth issues
> LC-135: more error handling for auth issues

- src/ui/controllers/profile.ts
- session null checker on self-signup
> fix-session-null-checker

- src/ui/controllers/profile.ts
- src/ui/controllers/user.ts
- sorting professions so 'i dont know' is at bottom of list
> fix-sorting-professions

- src/ui/controllers/profile.ts
> fix-resolve-uri-issue

- docker-compose.yaml
> chore-update-docker-compose-0606

- src/ui/page/profile/view.html
> LC-230 - adding change email link

- docker-compose.yaml
- src/lib/datetime.ts
- src/ui/component/DisciteCourse.html
- src/ui/component/Rightbox.html
- src/ui/component/Tile.html
- src/ui/component/disciteParts/DisciteCourseProperties.html
- src/ui/component/disciteParts/DisciteModuleProperties.html
- src/ui/controllers/course/index.ts
- src/ui/controllers/errorHandler.ts
- src/ui/controllers/home.ts
- src/ui/page/course/noModuleCourse.html
- src/ui/page/home.html
- src/ui/server.ts
- handling course with no modules on home screen
- adding logic to profile checker to only fire when running locally
> LC-227: Handling modules with no modules on home screen

- docker-compose.yaml
> chore-update-dc-1406

- src/ui/assets/styles/main.scss
- src/ui/page/profile/grade.html
- src/ui/page/profile/interests.html
- src/ui/page/profile/organisation.html
- src/ui/page/profile/otherAreasOfWork.html
- Added legend tag to profile forms
> add missing legend nodes

- src/lib/ui/courseCallToAction.ts
- src/ui/component/DisciteFeedback.html
- src/ui/component/disciteParts/DisciteCourseActions.html
- src/ui/component/disciteParts/DisciteModuleActions.html
- src/ui/page/booking/choose-date.html
- src/ui/page/booking/payment-options.html
- added descriptive links for screen readers on
- Start link for courses/modules 
- Add to learning plan link 
- Leave feedback link
- I do not want to leave feedback link
- Start this course link for elearning ('this course' text has been removed for consistency with the rest of the start links)
> Non descriptive links

- .gitignore
- src/locale/en.json
- src/ui/assets/styles/common/_variables.scss
- src/ui/page/profile/edit.html
- Added error messages for profile edit pages
> fixed generic error messages for profile page

- docker-compose.yaml
> chore-1907-docker-tags

- src/ui/component/ProfileEditForm.html
- src/ui/page/profile/organisation.html
removed redundant empty class
resized main column to be consistent with equivalent profile page
added filler column
> fixed page width for organisations setup page

- src/lib/config/featureConfig.ts
- src/lib/xapi.ts
- src/ui/controllers/user.ts
- src/ui/controllers/xapi.ts
- src/ui/server.ts
We check for the type and verb of the statement and if it's of a type Elearning and experineced verb then it returns and doesn't make a payload. Otherwise it does.
> Filtering out Elearning experienced statements

- src/lib/config/corsConfig.ts
- src/lib/config/luscaConfig.ts
- src/ui/server.ts
- adding env logic to accept traffic from non-prod cdns
- adding env logic for csp
> fix: adding-env-logic-to-cors-lusca

- src/ui/assets/styles/common/_global.scss
- src/ui/assets/styles/common/_variables.scss
- src/ui/assets/styles/components/_booking.scss
- src/ui/assets/styles/components/_header.scss
- src/ui/assets/styles/main.scss
- https://cshrdigitalandanalysis.atlassian.net/browse/LC-190
- css updates for accessibility
- replacing https://github.com/Civil-Service-Human-Resources/lpg-services/pull/606/files
> fix: accessibility updates

- docker-compose.yaml
> chore: updating docker images

- docker-compose.yaml
- src/lib/model.ts
- src/lib/ui/courseCallToAction.ts
- src/ui/assets/styles/common/_global.scss
- src/ui/component/DisciteModule.html
- src/ui/controllers/course/index.ts
- src/ui/page/course/blended.html
- src/ui/page/course/link.html
- src/ui/page/course/video.html
- https://cshrdigitalandanalysis.atlassian.net/browse/LC-235
- associated learning domain, controller and template logic 
- replacing https://github.com/Civil-Service-Human-Resources/lpg-services/pull/606/files and https://github.com/Civil-Service-Human-Resources/lpg-services/pull/602
> LC-235 - logic for associated learning modules

- src/ui/controllers/course/index.ts
- https://cshrdigitalandanalysis.atlassian.net/browse/LC-254
- encoding e-learning url to handle special chars
- replacing https://github.com/Civil-Service-Human-Resources/lpg-services/pull/606/files
> LC-254: e-learning module not showing as completed

- src/lib/config/passport.ts
- src/lib/identity.ts
- src/lib/registry.ts
- src/ui/controllers/profile.ts
- src/ui/controllers/user.ts
Fixes for all the issues to do with the change email on profile page scenario.
> Bugfix lc 14 find old org code

- src/lib/config/passport.ts
- src/lib/model.ts
- src/lib/registry.ts
- src/lib/ui/courseCallToAction.spec.ts
- src/lib/ui/profileChecker.spec.ts
- src/lib/ui/profileChecker.ts
- src/ui/controllers/profile.ts
- src/ui/controllers/user.ts
Fix for org page being displayed + 1 times.
> Bug fix lc 327 org being called more than once

- src/ui/controllers/booking/booking.ts
- src/ui/controllers/home.ts
- src/ui/controllers/learning-record/index.ts
- src/ui/controllers/search.ts
- src/ui/controllers/user.ts
- src/ui/controllers/xapi.ts
TS/node versions updated on the app. ts-igoring some of the warnings as we know these already work, and do not want to explicitly cast
> chore: fixing typescript warnings

- src/lib/identity.ts
- src/lib/learnerrecord.ts
- src/lib/purchase-orders.ts
- src/lib/registry.ts
- src/lib/reports.ts
- src/lib/service/catalog/index.ts
- src/lib/service/skills/index.ts
- src/ui/controllers/user.ts
- updating maxSockets and maxFreeSockets config for HTTP as per MS request
> perf: updating maxSockets and maxFreeSockets config for HTTP

- src/ui/controllers/booking/booking.ts
- src/ui/controllers/home.ts
- src/ui/controllers/learning-record/index.ts
- src/ui/controllers/search.ts
- src/ui/controllers/user.ts
- src/ui/controllers/xapi.ts
TS/node versions updated on the app. ts-igoring some of the warnings as we know these already work, and do not want to explictly cast.
Duplicate PR of https://github.com/Civil-Service-Human-Resources/lpg-services/pull/631, but needed for release e.
> chore: fixing ts errors

- src/lib/identity.ts
- src/lib/learnerrecord.ts
- src/lib/purchase-orders.ts
- src/lib/registry.ts
- src/lib/reports.ts
- src/lib/service/catalog/index.ts
- src/lib/service/skills/index.ts
- src/ui/controllers/booking/booking.ts
- src/ui/controllers/home.ts
- src/ui/controllers/learning-record/index.ts
- src/ui/controllers/search.ts
- src/ui/controllers/user.ts
- src/ui/controllers/xapi.ts
Release branch for performance release e
Contains PRs:
#609
#615
#639
_Replacing https://github.com/Civil-Service-Human-Resources/lpg-services/pull/638, as branch name had a forward slash char which causes issues when tagging in docker._
_Renamed branch from `releases/performance-release-e` to `releases-performance-release-e`_
> Releases - Performance release e

- src/lib/model.ts
Page breaks so we added an if statement to check if the events length is bigger than 0 and if the events is not null
> LC-291 fixing course which has a F2F module with no event

- src/ui/component/TypeAhead.html
- src/ui/controllers/user.ts
- src/ui/page/profile/email.html
- src/ui/page/profile/organisation.html
> Bug fix lc 14 accessibility

- src/ui/component/DisciteCourse.html
Booked module duration removed as is superseded by course duration
> LC-192 home booked module duration

- src/lib/model.ts
- src/ui/controllers/xapi.ts
Events chronological ordering.
> Hotfix duration fix event ordering

- .gitignore
- package-lock.json
- src/lib/config/index.ts
- src/lib/config/luscaConfig.ts
- src/ui/component/Header.html
- src/ui/component/HeaderNoNav.html
- src/ui/component/Page.html
- src/ui/server.ts
- test/webdriver/package-lock.json
As previous PR 629, lining up merge for master branch
> LC-429: Azure CDN for static assets

- src/ui/controllers/booking/cancel.ts
When a user tries to cancels a booking without choosing a reason then they are displayed with an 'ouch' page. This branch fixes it and displays an error to the user notifying them that they need to choose a reason
> fix-cancellation-bug

- src/lib/model.ts
- src/lib/registry.ts
- src/ui/controllers/profile.ts
- src/ui/controllers/user.ts
- src/ui/server.ts
* Added userId so that usage of HATEOAS is reduced (fewer calls)
* unified axios and traverson handler in patchSivilServant handler
* Bumped version of appInsights to 1.5.0 and change order of initialization so that appInsights will track the dependencies now
> Profile page improvements

- src/ui/page/skills/choose-quiz.html
- src/ui/page/skills/introduction.html
- src/ui/page/skills/quiz-history.html
- updating h tags on quiz history page to be semantically correct
> LC-714 - Skills accessibility h tags

- src/ui/component/disciteParts/DisciteModuleActions.html
- updating description for start module links on course overview
> LC-190: updating description for start module links on course overview

- docker-compose.yaml
- package-lock.json
- package.json
- src/lib/ui/moduleCallToAction.ts
- src/ui/component/disciteParts/DisciteModuleActions.html
- src/ui/page/home.html
- src/ui/page/skills/quiz-summary.html
- test/webdriver/package-lock.json
- general tidy up for docker images, npm dependencies
> Chore - General tidyup

- src/ui/assets/js/main.js
- src/ui/assets/styles/components/_govuk-related-items.scss
- src/ui/assets/styles/components/_leftSearchBox.scss
- src/ui/component/LeftSearchBox.html
- src/ui/component/Page.html
- src/ui/page/course/display-video.html
Adding accessibility to search filters in LPG and fixing video mp4 in display-video.htm
> LC-728-search-filters-accessibility

- src/ui/page/accessibility-statement.html
Changes defined in this tickets are removed.
> LC-782 Changes defined in this tickets are removed.

- src/ui/assets/js/main.js
- src/ui/assets/styles/components/_govuk-related-items.scss
- src/ui/assets/styles/components/_leftSearchBox.scss
- src/ui/component/LeftSearchBox.html
- src/ui/page/accessibility-statement.html
- src/ui/page/course/display-video.html
This PR is to remain in Draft status until the release deployed into production successfully. Then it will be merged into master.
> Idt-release-1.0 (LC-781 - IDT Release 1.0)

- docker-compose.yaml
- src/lib/learnerrecord.ts
- src/lib/model.ts
- src/lib/service/catalog/index.ts
- src/ui/controllers/home.ts
- src/ui/controllers/suggestion.ts
- src/ui/controllers/user.ts
- src/ui/page/suggested.html
- src/ui/server.ts
idt-release-2.0 - Release went live successfully so now it is ready to merge.
> idt-release-2.0

- src/ui/page/privacy.html
Update privacy notice content.
> Lc 844 update privacy notice

- src/ui/page/learning-record/index.html
> LC-795-remove-content-referring-to-CSL

- src/ui/page/accessibility-statement.html
- Changes as per Google drive document
> LC-854 made requested changes to accessibility statement

- src/ui/page/privacy.html
- Changes requested to ensure compliance with Youtube APIs
- Contact details changed
> LC-844 update privacy notice to include Youtube privacy links

- src/ui/page/privacy.html
> LC-844 privacy statement changes

- Dockerfile
- src/ui/page/privacy.html
- updated privacy statement in line with latest requirements
> LC 990 update privacy statement

- src/ui/page/privacy.html
- Fixed spelling mistakes in privacy statement
> LC 1001 privacy statement spelling mistakes

- src/ui/page/accessibility-statement.html
- Updated accessibility statement as per GDS feedback
> LC 884 updated accessibility statement

- src/lib/model.ts
- src/lib/registry.ts
- src/lib/service/catalog/index.ts
- Audience relevancy code now takes organisation hierarchy into account
> LC 1075 audience course overview fix

- src/locale/en.json
This change updates the archived notification header to be more friendly:
> Update archived notification heading

- src/ui/page/privacy.html
This change updates the Privacy page with an updated "Retention" section to reflect new information.
> Update retention policy in Privacy page

- Dockerfile.dev
- src/ui/component/Header.html
- src/ui/component/HeaderNoNav.html
- src/ui/page/cookies.html
- src/ui/page/error.html
- src/ui/page/error/404.html
- test/webdriver/src/test/login.spec.ts
- test/webdriver/src/test/profile.spec.ts
- Remove smart survey link from Beta banner
- Remove all references/tests to smart survey
- Add Dev Dockerfile
> Idt feature lc 1153 beta banner survey

- src/ui/controllers/feedback.ts
> Idt hotfix v1.3.1

- src/ui/controllers/xapi.ts
> Idt release v1.6.0

- src/lib/config/index.ts
- src/ui/controllers/user.ts
- src/ui/page/privacy.html
- test/webdriver/src/test/login.spec.ts
This change updates the feedback and support email addresses in the Privacy Policy page.
> LC-1507: Update privacy policy emails

- src/ui/page/learning-record/course-result.html
- Module result splash screen now shows a nicer message to the user if they passed the module
> LC 1954 remove hardcoded course result

- src/lib/learnerrecord.ts
- src/lib/logger.ts
- src/lib/model.ts
- src/lib/service/catalog/index.ts
- src/lib/service/learnerRecordAPI/models/record.ts
- src/lib/service/learnerRecordAPI/moduleRecord/models/moduleRecord.ts
- src/ui/controllers/course/index.spec.ts
- src/ui/controllers/course/index.ts
- src/ui/controllers/home.ts
> Idt release v1.9.0

- src/lib/model.ts
- src/lib/service/learnerRecordAPI/courseRecord/models/courseRecord.ts
- src/ui/controllers/learning-record/index.ts
- `learning-record` now uses the required learning audience to calculate how far along a user is with their mandatory learning
- Implemented `getDisplayStateForCourse` which can be used for the homepage at a later date
> LC-2063 learning record bug

- src/lib/model.ts
- src/ui/controllers/learning-record/index.spec.ts
- src/ui/controllers/learning-record/index.ts
- Refactored the `getDisplayStateForCourse` function
- Added unit tests
> LC 2063 Learning record bug - tidyup and tests

- src/lib/config/index.ts
- src/lib/config/luscaConfig.ts
- Added new GA4 endpoints to the content security policy
> LC 2286 ga4 csp

- src/ui/controllers/course/index.ts
- Correctly search launch link for youtube URL
> Fix youtube

- src/lib/config/index.ts
- src/lib/config/passport.ts
- src/lib/identity.ts
- src/lib/model.ts
- src/lib/service/civilServantRegistry/csrsService.spec.ts
- src/lib/service/civilServantRegistry/csrsService.ts
- src/lib/service/civilServantRegistry/models/getOrganisationsResponse.ts
- src/lib/service/civilServantRegistry/models/organisationalUnitTypeAhead.spec.ts
- src/lib/service/civilServantRegistry/models/organisationalUnitTypeAhead.ts
- src/lib/service/civilServantRegistry/organisationalUnit/organisationUnitClient.ts
- src/lib/service/civilServantRegistry/organisationalUnit/organisationalUnitCache.ts
- src/lib/utils/cache.ts
- src/lib/utils/cacheableObject.ts
- src/lib/utils/cacheableObjectCache.ts
- src/ui/server.ts
- Include new orgs V2 endpoint
- Add Domains to organisational unit object
- Filter organisational unit dropdown by domain (for all users)
- Cache enhancements
> LC 2473 restrict org by domain

- src/lib/model.ts
- src/ui/component/DisciteCourse.html
- Due by date is now set to the end of the day, rather than the beginning
- Removed unused functions
- Frontend uses new due by date function to correctly display the due by date
> LC-2671 fix due by date calculation

- src/lib/learnerrecord.ts
- src/lib/service/cslService/cslServiceClient.ts
- src/lib/service/cslService/models/CancelBookingDto.ts
- src/lib/utils/SessionUtils.ts
- src/ui/controllers/booking/cancel.ts
- Move cancel booking logic to csl-service
- Refactor cancel booking code
> LC 2216 cancel booking

- src/lib/model.ts
- src/ui/component/DisciteCourse.html
- Required learning deadline now renders with respect to Azure server time using `moment` with `utc`
> LC 2751 fix required learning deadline display

- src/lib/service/cslService/models/UserDto.ts
- src/lib/service/cslService/models/factory/UserDtoFactory.ts
- Check if Grade exists before attempting to set the grade ID when a user launches a module
> LC 2986 grade launch bug

- src/lib/service/cslService/models/UserDto.ts
- src/lib/service/cslService/models/factory/UserDtoFactory.ts
This change updates the UserDto model to include `organisationAbbreviation`, `professionName` and `gradeCode`.
>  LC-2977: MVP course completion report - Exported csv content

- src/lib/service/cslService/models/UserDto.ts
- src/lib/service/cslService/models/factory/UserDtoFactory.ts
- Inlcude line manager details in the userDTO when launching modules
> LC-3177 Add line manager details to the userDto

- src/ui/page/learning-record/index.html
This change updates the messaging of completed learning on Learning record pages:
* Replaces "You have X courses to complete this reporting year" to "You have X courses to complete."
* Replaces "You have completed 8 of your required learning courses this year and have X more to do." to "You have completed 8 of your required learning courses and have X more to do."
> LC-3007: Update completed learning text in learning record

- src/lib/model.ts
- src/lib/ui/moduleCallToAction.spec.ts
- src/lib/ui/moduleCallToAction.ts
- src/locale/en.json
- src/ui/assets/styles/components/_notification.scss
- src/ui/component/ArchivedWarning.html
- src/ui/component/NotificationBanner.html
- src/ui/component/disciteParts/DisciteModuleActions.html
- src/ui/page/course/face-to-face.html
- Introduce check on both the single-module-course and blended course pages for f2f modules that have no bookable events
- When a module has no bookable events, show an information message to the user
> LC-3277 f2f course no events

- src/ui/controllers/booking/cancel.ts
- Fix rendering of cancellation reasons
> LC 3322 cancellation reasons

- package-lock.json
- package.json
- src/ui/server.ts
- Alter `serve-static` settings to accomodate Azure Frontdoor
> LC-3346 serve static

- views/component/Banner.html
- views/page/search/index.html
Testing Document: https://cshrdigitalandanalysis.atlassian.net/wiki/spaces/LPG/pages/3883401217/LC-3225-Learner+UI+Status+messages
> LC-3225-DAC Audit-Learner UI Status messages

- README.md
- views/component/Footer.html
- views/component/Header.html
- views/component/HeaderNoNav.html
- views/nunjucks/root/footer.njk
- views/nunjucks/root/header.njk
- views/page/error.html
- views/page/error/404.html
Testing document: https://cshrdigitalandanalysis.atlassian.net/wiki/spaces/LPG/pages/3884089345/LC-1297-Remove+the+Platform+keyword+from+the+CSL+UI#lpg-services.1
> LC-1297-Remove the "Platform" keyword from “Civil Service Learning Platform“ on the CSL UI

- src/lib/model.ts
- src/lib/ui/courseCallToAction.ts
- src/ui/controllers/course/models/factory.ts
- src/ui/controllers/learning-record/index.ts
- views/page/learning-record/course-result.html
This change:
* fixes a bug to take learning period into account when calculating the completed module count
* refactors the course-result page
> LC-2934: Fix module count bug on course result

- package.json
- src/ui/controllers/learning-record/index.ts
- test/controller/learningRecord/index.spec.ts
- views/page/learning-record/index.html
This change changes the message on the _Learner record_ page so that it displays the appropriate text according to whether the user has no required learning, has or hasn't completed their required learning.
> LC-1516: Fix conflicting messages bug

- package-lock.json
- views/page/learning-record/index.html
This change updates the heading in the Learner Record page so that it matches other pages' headings (homepage, suggestions for you)
> LC-3618: Update learner record heading styling

- views/assets/styles/common/_layout.scss
- views/assets/styles/components/_home-tile.scss
- views/assets/styles/components/_tile.scss
- views/assets/styles/main.scss
- views/component/Tile.html
This change increases the spacing for courses in Suggestions for You page
> LC-3617: Increase spacing in suggestions for you page

- src/lib/service/civilServantRegistry/csrsService.ts
- src/lib/service/cslService/cslServiceClient.ts
- src/ui/controllers/profile/pages/areaOfWork.spec.ts
- src/ui/controllers/profile/pages/areaOfWork.ts
Testing document: https://cshrdigitalandanalysis.atlassian.net/wiki/spaces/LPG/pages/3972825099/LC-3563+Amend+the+learner+s+profession+update+process+to+update+the+Registered+Learners+Report+data
> LC-3563 - Amend learner profession update process to update registered learners report data

- views/nunjucks/course/blended.njk
- Alter text on course overview to advise learners that they must complete all mandatory modules to complete the course
> LC-3788 mandatory module text
