src/ui/component/Layout.html, src/ui/controllers/course/index.ts, src/ui/page/course/display-video.html, src/ui/page/course/link.html, src/ui/page/course/video.html
This bug fix addresses courses with single link or video modules opening directly to the module instead of the course overview page.
Renamed video.html to display-video.html
Created video.html - now an overview page for a single video
Created link.html
Changed course/index.html such that video and link now have the same behaviour as blended and file
=> LPFG-780: Links and Videos now open overview page first

package.json
Updating protobuf version as recommended by GH
The `@types/` package is unaffected.
=> LPFG-688: updating protobuf version

.gitignore, src/locale/en.json
- removed 'Blog' entry from en.json. Since there are no blog course types, this only affects the search filter option.
=> LPFG-963 Remove blog from search filters

docker-compose.yaml, src/lib/model.ts, src/lib/service/catalog/api.ts, src/lib/service/catalog/index.ts, src/ui/assets/styles/common/_global.scss, src/ui/component/Search.html, src/ui/page/search/index.html
_Related PRs:
https://github.com/Civil-Service-Human-Resources/lpg-learning-catalogue/pull/63
https://github.com/Civil-Service-Human-Resources/lpg-management/pull/134_
- updating search on lpg-services to use new controller on lpg-learning-catalogue
- adding status filters to search query
- removing redundant resource/module code
- changed the results found message and position after discussion with Jane and Dan. Since there has been no UR on the term, the decision was made to keep the pattern like the search results on gov.uk.
- added user search term to search box
=> LPFG-983: Search admin

src/lib/model.ts
This is a fix that solves the issue of courses appearing as already in your learning plan when searching.
A courses audience is now set to mandatory base on the department of the current user and if the audience is of type 'Required Learning'.
=> LPFG-997: Set mandatory base on audience department and type

src/ui/component/LeftSearchBox.html
Found 2 id's that shared the same name on the search results page (id="q"). Changed the id on a hidden input field in the search filters form to id="query". Tested that form and filters still work as expected.
=> LPFG-1011 duplicate IDs on search page

src/lib/learnerrecord.ts, src/lib/model.ts, src/ui/controllers/booking/booking.ts, src/ui/page/booking/choose-date.html
**Should be merged with LPFG-1262 in learner record**
If a user has already booked onto an event, they shouldn't be able to go through the booking journey again. Now if a user is booked, the select button is replaced with 'Already booked'.
- Added getActiveBooking function to **learnerrecord.ts**
- Added isLearnerBooked boolean to Event in **model.ts**
- Check and set if learner is booked on each event in **booking.ts**
- If learner is booked show 'Already booked' in **chose-date.html**
=> LPFG-1262: Show already booked if already booked

src/ui/controllers/booking/booking.ts
If no line manager is set when trying to make a booking onto an event, the learner should be redirected to the profile page.
=> LPFG-1154 Booking without a line manager

src/lib/ui/courseCallToAction.spec.ts, src/lib/ui/courseCallToAction.ts, src/ui/component/disciteParts/DisciteModuleActions.html
If a booking has been cancelled, the booking link should appear next to the booking to allow for rebooking. Previously the booking url and message were deleted in **courseCallToAction.ts** so nothing would be displayed, that has been removed here so that booking link is displayed.
=> LPFG-1216: Rebooking

src/ui/assets/styles/components/_leftSearchBox.scss, src/ui/component/LeftSearchBox.html
- Added a link to the filters form that clears the form of all filters but keeps the search term
- Duplicated the Apply filters button and added at the top of the filters section, complete with the clear filters link, as per the design
=> LPFG-1234 Clear filters link

src/lib/config/index.ts
Swapping references to local.cshr.digital virtual hosts to use localhost instead. The .cshr.digital host was causing problems locally.
See related PR:
https://github.com/Civil-Service-Human-Resources/identity-service/pull/125
https://github.com/Civil-Service-Human-Resources/lpg-management/pull/232
=> chore: updating local dev config to use localhost

src/lib/model.ts
This hot fix is to fix the duration field being empty in the home screen. If there are no modules or modules with no event duration we will display '0 minutes' instead of leaving it blank.
=> Hotfix display duration 0 minutes

src/ui/controllers/xapi.ts
- remove explicit cast ts warning
=> chore: ts warning

.prettierrc.json, src/lib/config/passport.ts, src/lib/model.ts, src/lib/registry.ts, src/lib/ui/profileChecker.ts, src/ui/component/ProfileEditForm.html, src/ui/controllers/profile.ts, src/ui/controllers/user.ts, src/ui/factory/agencyTokenFactory.ts, src/ui/model/agencyToken.ts, src/ui/page/profile/email.html
Refactoring change your email flow. If a user doesn't have an organisation, we should just send the user to the change email form because we cant check whether they are an agency token user. 
Furthermore, this was only handling users that were either Whitelisted or Agency tokens, but this did not handle users who had been invited via IDM. Updating logic accordingly.
Adding model and factory classes for agency token objects.
Lots of prettier formatting updates.
=> LC-14: refactoring change your email

src/ui/server.ts
Adding an empty HTTP handler for xAPI e-learning statements. This should return HTTP 200, instead of 404s, and should reduce the volume of error logs the app throws.
=> Feature empty handler for xapi learning locker

src/ui/assets/styles/components/_leftSearchBox.scss, src/ui/component/LeftSearchBox.html
On mobile view, the search page will show a hide/show search filters checkbox, not visible during standard desktop view. Adding an aria-hidden = "true" to the element so that it is not narrated by screen readers.
=> LC-190: accessibility update for search page

src/lib/config/corsConfig.ts, src/lib/config/luscaConfig.ts
- Normalised CORS functionality as it longer needs to differentiate between .cshr.digital/.civilservice.gov.uk
- Updated lusca config to cope with new test env URLs
=> LC 883 - removed reference to cshr.digital in CORS/csp configurations

src/lib/model.ts
- getRelevance function now correctly uses the user's grade *code* to compare for relevance, rather than the entire object
=> LC-1072 Audiences fix

src/lib/config/index.ts, src/ui/page/accessibility-statement.html, src/ui/page/contact-us.html, src/ui/server.ts
- Updated email address on the contact us page and the accessibility statement
- Updated contact email to be fully configurable. Not a totally ideal option but until a CMS is implemented it's the best thing for now
- Removed hardcoded email address / default value for CONTACT_EMAIL. This will now be supplied as a secret value from Terraform
=> LC-1094 Updated contact email

src/locale/en.json, src/ui/assets/styles/components/_notification.scss, src/ui/assets/styles/main.scss, src/ui/component/ArchivedWarning.html, src/ui/page/course/blended.html, src/ui/page/course/display-video.html, src/ui/page/course/elearning.html, src/ui/page/course/face-to-face.html, src/ui/page/course/file.html, src/ui/page/course/link.html, src/ui/page/course/noModuleCourse.html, src/ui/page/course/video.html
This change:
* Creates a Svelte component `ArchivedWarning`
* Creates a `SCSS` styling for `ArchivedWarning`
* Adds entries for archived warning text on internationalisation files
* Adds warnings to course pages if a course is archived (see screenshots)
* Removes interactions from course pages if a course is archived (see screenshots)
* No warning
* Interactions are visible
* Archived warning visible
* Interactions hidden
Removes:
* Approval warning
* "How to get a PO number" link
* "View availability" button
Removes the "Start this learning" button
Removes the "Start" link
=> Add notifications for archived courses

src/locale/en.json, src/ui/page/booking/ouch.html, src/ui/page/error.html
This change updates the wording of the error (previously "Ouch").
After stopping Learner Record:
=> Updated wording of error messages

src/ui/component/Footer.html, src/ui/page/error.html, src/ui/page/error/404.html
This change updates the "Crown copyright" footer link to the correct address
=> Update Crown Copyright link

src/lib/config/featureConfig.ts, src/ui/controllers/course/index.ts, src/ui/controllers/xapi.ts
- Prevent statements from going to learning locker
- Only update E-Learning on launch and COMPLETED verb
- Check if user is undefined and return if so, preventing the exception that occurs
- Wrap the learner record sync in a try catch to prevent container crashes
=> LC 1716 manage learne record API calls

package.json, src/lib/learnerrecord.ts, src/lib/model.ts, src/lib/service/catalog/courseCatalogueClient.ts, src/lib/service/catalog/index.ts, src/lib/service/learnerRecordAPI/courseRecord/client.ts, src/lib/service/learnerRecordAPI/courseRecord/models/courseRecord.ts, src/lib/service/learnerRecordAPI/models/record.ts, src/lib/service/learnerRecordAPI/moduleRecord/models/moduleRecord.ts, src/ui/controllers/home.ts, src/ui/controllers/learning-record/feedback.ts, src/ui/server.ts
- Fixed homepage logic. Homepage now respects all relevant modules in a course and calculates completion statuses according to learning period. Refactored the `courseRecord` class to achieve this.
- Introduced a `CourseRcd` interface to ensure compatibility with legacy courseRecord and current courseRecord with a long-term aim to move away from the legacy `courseRecord` and `getRawLearnerRecord` code
- Added new `npm` command for running with just the TS compiler
=> LC 2102 homepage extra module fix

src/lib/model.ts, src/lib/service/catalog/suggestedLearning/suggestedLearningService.spec.ts, src/lib/service/catalog/suggestedLearning/suggestedLearningService.ts
- `getGradeCode` - a new method on the user class which returns an empty string if the user's grade is null
- Suggestions for you now make use of the new above method to calculate suggested learning, even when the grade is null
=> LC-2258 suggested learning grade code bug

src/ui/assets/js/video.js
This change replaces the use of jQuery to detect the video player with the basic `document.getElementById` function. The issue arose after updating jQuery to a version after 3.0, which completely removed the `$().size()` function.
=> Fix YouTube player issue

src/ui/controllers/user.ts
Line manager (line-manager param) fails the case statement and defaults to redirecting to /profile - include a case statement for line manager that unfortunately does nothing.
Profile endpoints should be split out to separate,defined functions in the future to avoid strange behaviour.
=> Fix line manager link

src/ui/page/course/display-video.html
This change 
* Updates the back link at the top of the video display page from "Find another course", which takes the user to the "Suggestions for you page", to "Return to course", which takes the user back to the course overview page.
* Removes unused links in the video display page.
=> LC-2961: Update backlink for video modules

src/lib/service/civilServantRegistry/models/organisationalUnitTypeAhead.ts
- The collator object was not being serialized correctly when being fetched from the cache. This has been moved to a private function instead
=> LC-3009 fix fetch organisation typeahead

src/ui/controllers/profile.ts
This change gives `areasOfWork` for each user the correct structure after initial profile completion so that it can be read by the Profile page, instead of showing as "undefined".
=> LC-3022: Fix bug setting primary area of work as undefined

src/ui/controllers/learning-record/index.ts
This change sets the URL to redirect when a module is still in progress to the course overview page instead of the homepage
=> LC-2633: Navigate users to course overview after leaving a module in progress

src/ui/assets/js/govuk_frontend_toolkit/govuk/govuk-template.js, src/ui/assets/styles/components/_header.scss, src/ui/component/Header.html, src/ui/component/HeaderNoNav.html
- The arrow glyphs used to show when the menu is collapsed/expanded in mobile view are now in a separate span tag which is `aria-hidden`
=> LC-3215 replace css arrow glyph with hidden tag

locale/en.json, package-lock.json, src/lib/service/civilServantRegistry/models/patchCivilServant.ts, src/ui/controllers/profile/models/interests/editInterestsPageModel.ts, src/ui/controllers/profile/pages/interests.spec.ts, views/page/profile/view.html, views/page/suggested.html
This change:
* Removes the restriction to allow interests from user profile to be empty
* Updates the profile page UI so that when no interests are selected, a "No interests selected" text appears
* Updates the Suggestions for You page so that when no interests are selected, a "No interests selected" text appears
* Updates the CSRS `PATCH` logic so that it can send empty interests list to the endpoint.
* Updates the unit tests to check if the user now gets redirected when no interests are selected
=> LC-3374: User can remove all interests from profile

views/assets/styles/common/_global.scss, views/component/Checkboxes.html, views/component/NewRadios.html
- Fix non-text contrast by bringing green CTA button's focus state inline with GDS buttons: https://design-system.service.gov.uk/components/button/
- Fix other accessibility issue where names and ids for profile checkboxes/radios had spaces in
=> LC-3224 button focus non-text contrast

src/lib/learnerrecord.ts, src/lib/service/learnerRecordAPI/courseRecord/models/courseRecord.ts, src/ui/controllers/booking/booking.ts, src/ui/controllers/booking/cancel.ts, src/ui/controllers/learning-record/index.ts
- Remove `getRecord`, which relied on the `/records` endpoint. This endpoint has now been removed from the learner record API
- Move logic that relied on `getRecord` over to the `GET /course_records` models
=> Remove reliance on old learner record endpoints
